config/routes.rb
Rails.application.routes.draw do



  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users #do
    # resources :following, only: :index
    # resources :followers, only: :index

    # member do
    #   get :following, :followers
    # end
  # end

  get "users/:id/:state", to: "relationships#index", as: :relationships

  # resources :posts,			except: %i(edit new update)
  # resources :posts do
  resources :comments,	only: [:create, :destroy]
  # end

  resources :posts, except: %i(edit new update) do
    member do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :relationships,       only: [:create, :destroy]
  get 'tags/:tag', to: 'posts#index', as: :tag
  get "posts/:search", to: "posts#index", as: :search
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@users = User.paginate(page: params[:page])

  	if logged_in?
      @post = current_user.posts.build
  		@feed_items = current_user.feed.paginate(page: params[:page])
  	end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% if logged_in? %>
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
  <div class="row">
    <aside class="col-md-12">
      <section class="micropost_form">
        <%= render 'shared/post_form' %>
      </section>
    </aside>
  </div>
    <div class="col-md-8">
      <%= render 'shared/feed' %>
    </div>
<% else %>


  <header class="intro-header">
        <div class="container">
          <div class="intro-message">
            <h1>Landing Page</h1>
            <h3>A Template by Start Bootstrap</h3>
            <hr class="intro-divider">
            <ul class="list-inline intro-social-buttons">
              <li class="list-inline-item">
                <%= link_to "Sign in", login_path, class: "btn btn-default btn-lg" %>
              </li>
              <li class="list-inline-item">
                <%= link_to "Sign up", new_user_path, class: "btn btn-success btn-lg" %>
              </li>
            </ul>
          </div>
        </div>
  </header>
<% end %>