config/routes.rb
Rails.application.routes.draw do



  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users #do
    # resources :following, only: :index
    # resources :followers, only: :index

    # member do
    #   get :following, :followers
    # end
  # end

  get "users/:id/:state", to: "relationships#index", as: :relationships

  # resources :posts,			except: %i(edit new update)
  # resources :posts do
  resources :comments,	only: [:create, :destroy]
  # end

  resources :posts, except: %i(edit new update) do
    member do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :relationships,       only: [:create, :destroy]
  get 'tags/:tag', to: 'posts#index', as: :tag
  get "posts/:search", to: "posts#index", as: :search
end

app/views/shared/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
  <div class="form-group">
    <%= f.text_area :content, class: "form-control", rows: "3"%>
    <%= hidden_field_tag :post_id, @post.id %>
  </div>
    <div class="col-xs-2">
  <%= f.submit "Reply", class: "btn btn-primary",id: "submit" %>
    </div>
 <% end %>



 <script type="text/javascript">
  $("#submit").on("click", function(e){
    e.preventDefault();
    var content = $("#comment_content").val();
    if(content){
      $.ajax({
        url: "/comments",
        type: "post",
        dataType: "json",
        data: {comment: {content: content, post_id: $('#post_id').val()}},
        success: function(res){
         $(".comments").prepend(res.comment_data);
         $("#comment_content").val("");
        }
      })
    }
  })
 </script>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="feed">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_like_form.html.erb
<% if @post.likes.find_by(user_id: current_user.id)%>
  <%= link_to "Liked", @post.likes.find_by(user_id: current_user.id),class: "like", method: :delete %>
<% else %>
    <%= form_for @post.likes.build do |f| %>
        <%= f.hidden_field :user_id , value: current_user.id %>
        <%= f.hidden_field :post_id , value: @post.id %>
        <%= f.submit "Like", class: "like_form" %>
    <% end %>
<% end %>

  <p class="likes"><%=	 @post.likes.count %></p>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>

  <div class="input-group">
   <span class="input-group-addon">Title</span>
    <%= f.text_field :title, placeholder: "Compose title..." ,class: "form-control"%>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post...",class: "form-control" %>
  </div>
  <div class="input-group">
    <span class="input-group-addon">Tag</span>
    <%= f.text_field :tag_list, class: "form-control"%>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>
<!-- <script type="text/javascript">
  $(".btn-primary").on("click",function(e){
    e.preventDefault;
    title = $("#post_title").val();
    content = $("#post_content").val();
    if(title && content){
      $.ajax({
        url: "/posts",
        type: "post",
        dataType: "json",
        data: {post: {content: content, title: title}},
        success: function(res){
         $(".posts").prepend(res.post_data);
        }
      })
    }
  })
</script> -->

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <!-- <a href="<%#= following_user_path(@user) %>"> -->
  <%= link_to relationships_path(id: @user.id, state: :following), class: "btn btn-primary" do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  <% end %>
  <%= link_to relationships_path(id: @user.id, state: :followers), class: "btn btn-info" do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<span><%= current_user.name %></span><br>
<span><%= pluralize(current_user.posts.count, "post") %></span><br>
<span><%= link_to "view my profile", current_user %></span>