config/routes.rb
Rails.application.routes.draw do



  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users #do
    # resources :following, only: :index
    # resources :followers, only: :index

    # member do
    #   get :following, :followers
    # end
  # end

  get "users/:id/:state", to: "relationships#index", as: :relationships

  # resources :posts,			except: %i(edit new update)
  # resources :posts do
  resources :comments,	only: [:create, :destroy]
  # end

  resources :posts, except: %i(edit new update) do
    member do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :relationships,       only: [:create, :destroy]
  get 'tags/:tag', to: 'posts#index', as: :tag
  get "posts/:search", to: "posts#index", as: :search
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :taggings
  has_many :tags, through: :taggings

  default_scope -> { order(created_at: :desc) }

  validates :content, presence: true
  validates :title, presence:true

  def Post.tagged_with(name)
    tag = Tag.find_by_name(name) ? tag.posts : Post.none
  end

  def total_like
    likes.count
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    tags_name = names.split(",").map! &:strip

    exist_tags = Tag.where("name IN (?)", tags_name)

    not_exist_tags = []

    tags_name.each do |name|
      # Tag.where(name: n.strip).first_or_create!
      tag = exist_tags.detect{|tag| tag.name == name}

      next if tag

      # Build insert query
      not_exist_tags << Tag.new(name: name)
    end

    Tag.import not_exist_tags, validate: false
  end

  scope :search, ->(search){
    where("title LIKE ?","%#{search}%")
  }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def new
		@post = Post.new

	end

	def show
		@post = Post.find(params[:id])
		@comment = @post.comments.build
		@comments = @post.comments.all
	end

	def create
		@post = current_user.posts.new(post_params)
		if @post.save
			# byebug
			# render json: {
			# 	post_data: render_to_string(@post)
			# }
		redirect_to root_url
		else
			render "static_pages/home"
		end

	end

	def index
		if params[:tag]
      		@tag = Tag.find_by(name: params[:tag])
      		@post = Post.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 20)
		elsif params[:search]
					@post = Post.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 20)
		else
      		@post = Post.all.paginate(page: params[:page], per_page: 20)
		end
	end

	private

		def post_params
			params.require(:post).permit(:title,:content,:tag_list)
		end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
  <div class="post-preview">
    <%= link_to post.user.name, post.user %>
      <h2 class="post-title">
        <%= post.title %>
      </h2>
      <h3 class="post-subtitle">
        <%	 if post.content.length > 100 %>
            <%= post.content.to_s[0,99]%><%= link_to "...More" , post %></span><br>
        <%else %>
            <%= post.content %><br>
            <%= link_to "More" , post %>
        <% end %>
      </h3>

    <p class="post-meta">Posted by
      Posted <%= time_ago_in_words(post.created_at) %> <ago></ago></p>
  </div>
  <hr>

app/views/posts/index.html.erb
<% if @tag %>
  <h1>Tags: <%= @tag.name %></h1>
<% end %>
<div class="col-md-12">
  <% if @post %>
    <h3>Posts (<%= @post.count %>)</h3>
    <ol class="microposts">
      <%= render @post %>
    </ol>
    <%= will_paginate @post %>
   <% else%>
    <h1>Sorry, we cant find anything like this</h1>
  <% end %>
</div>

app/views/posts/show.html.erb
<h1><%= @post.content %></h1>
<p><%= render "shared/like_form" %> </p>
<p>Tags: <%= 	@post.tags.map(&:name).map {|t| link_to t, tag_path(t)}.join(",").html_safe  %></p>
<div class="col-md-8">
    <% if @post.comments.any? %>
      <ul class="comments">
        <%= render @comments %>
      </ul>
 
    <% end %>
 </div>
<%= render "shared/comment_form" %>	