config/routes.rb
Rails.application.routes.draw do



  root "static_pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users #do
    # resources :following, only: :index
    # resources :followers, only: :index

    # member do
    #   get :following, :followers
    # end
  # end

  get "users/:id/:state", to: "relationships#index", as: :relationships

  # resources :posts,			except: %i(edit new update)
  # resources :posts do
  resources :comments,	only: [:create, :destroy]
  # end

  resources :posts, except: %i(edit new update) do
    member do
      resources :likes, only: [:create, :destroy]
    end
  end
  resources :relationships,       only: [:create, :destroy]
  get 'tags/:tag', to: 'posts#index', as: :tag
  get "posts/:search", to: "posts#index", as: :search
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <ul class="list-inline">
      <li class="list-inline-item">
        <a href="#">Home</a>
      </li>
      <li class="footer-menu-divider list-inline-item">&sdot;</li>
      <li class="list-inline-item">
        <a href="#about">About</a>
      </li>
      <li class="footer-menu-divider list-inline-item">&sdot;</li>
      <li class="list-inline-item">
        <a href="#services">Services</a>
      </li>
      <li class="footer-menu-divider list-inline-item">&sdot;</li>
      <li class="list-inline-item">
        <a href="#contact">Contact</a>
      </li>
    </ul>
    <p class="copyright text-muted small">Copyright &copy; Your Company 2017. All Rights Reserved</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <%= link_to "Blog", root_path, class: "navbar-brand" %>
    </div>

    <div class="col-md-4">
      <div class="card my-4">
        <br>
      <div class="input-group">

        <!--<input type="text" class="form-control" placeholder="Search for...">-->
        <!--<span class="input-group-btn">-->
          <!--<input type="button" class="btn btn-secondary" type="button" value="Go">Go!</input>-->
        <!--</span>-->

        <%= form_tag(posts_path,method: :get, id: "form-control") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
          <span class="input-group-btn">
          <%= submit_tag "Search" ,class: "btn btn-secondary"%>
          </span>
        <% end %>
      </div>
    </div>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <% if logged_in? %>
            <% if current_user.admin? %>

          <li><%= link_to "Users", users_path %></li>
            <% end %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             Account <b class="caret"></b>
            </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", '#' %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
          </ul>
          </li>
         <% else %>
      <li><%= link_to "Log in", login_path %></li>
    <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    </div>
    <%= render "layouts/footer" %>

  </body>
</html>